# Generated by Django 4.2.6 on 2023-11-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("senha", models.CharField(max_length=50)),
                ("curso", models.CharField(max_length=20)),
                ("categoria", models.CharField(max_length=7)),
                ("contato_nunmero1", models.CharField(max_length=11)),
                ("contato_nunmero2", models.CharField(max_length=11)),
                ("foto_perfil", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
