# Generated by Django 4.2.7 on 2023-11-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('foto_perfil', models.TextField()),
            ],
            options={
                'db_table': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('aluno', 'Aluno'), ('monitor', 'Monitor')], max_length=10)),
                ('contato_numero_1', models.CharField(max_length=15)),
                ('contato_numero_2', models.CharField(max_length=15)),
                ('foto_perfil', models.TextField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.usuario')),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'monitores',
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interesse', models.DateTimeField(default='1970-01-01T00:00:00Z')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.monitor')),
            ],
            options={
                'db_table': 'interesse',
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('monitores', models.ManyToManyField(related_name='assuntos', to='users.monitor')),
            ],
            options={
                'db_table': 'assuntos',
            },
        ),
    ]
