# Generated by Django 4.2.6 on 2023-11-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contato_nunmero1',
            new_name='contato_numero1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contato_nunmero2',
            new_name='contato_numero2',
        ),
    ]
