# Generated by Django 4.2.7 on 2023-11-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_contato_nunmero1_user_contato_numero1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AddField(
            model_name="user",
            name="id_usuario",
            field=models.AutoField(primary_key=True, serialize=True),
            preserve_default=False,
        ),
    ]
