# Generated by Django 4.2.7 on 2023-11-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_monitor_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assunto',
            name='monitores',
        ),
        migrations.AddField(
            model_name='monitor',
            name='assuntos',
            field=models.ManyToManyField(related_name='assuntos', to='users.assunto'),
        ),
    ]
