# Generated by Django 4.2.7 on 2023-11-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_id_user_id_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuarios',
        ),
    ]
