# Generated by Django 4.2.7 on 2023-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_assunto_monitores_monitor_assuntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='assuntos',
        ),
        migrations.AddField(
            model_name='monitor',
            name='assuntos',
            field=models.TextField(blank=True),
        ),
    ]
