# Generated by Django 4.2.7 on 2023-11-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_monitor_assuntos_monitor_assuntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contato_numero_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contato_numero_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
