# Generated by Django 4.2.7 on 2023-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='categoria',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='curso',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=45),
        ),
    ]
