# Generated by Django 4.2.6 on 2023-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuarios_categoria_alter_usuarios_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
