# Generated by Django 4.2.7 on 2023-11-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
