# Generated by Django 4.2.7 on 2023-11-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contato_numero1',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contato_numero2',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
