# Generated by Django 4.2.7 on 2023-11-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_usuarios_contato_numero1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
