# Generated by Django 4.2.7 on 2023-11-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usuarios_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('id_monitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.usuarios')),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('assuntos_ensinados', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monitores',
            },
        ),
    ]
