# Generated by Django 4.2.7 on 2023-11-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_administrador_monitores'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='administradores',
        ),
    ]
