# Generated by Django 4.2.6 on 2023-11-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuarios_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='users.usuarios')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_dadas', to='users.usuarios')),
            ],
            options={
                'db_table': 'interesse',
            },
        ),
    ]
