import { Injectable, OnInit } from '@angular/core';
import { DjangoConnService } from './django-conn.service';

@Injectable({
  providedIn: 'root',
})
export class NavDataService {
  coursesList: any = [
    { name: 'Administração', id: 1 },
    { name: 'ADS', id: 2 },
    { name: 'Arquitetura e Urbanismo', id: 3 },
    { name: 'Artes Visuais', id: 4 },
    { name: 'Biomedicina', id: 5 },
    { name: 'Ciência de Dados', id: 6 },
    { name: 'Ciências Biológicas', id: 8 },
    { name: 'Ciências Contábeis', id: 9 },
    { name: 'Ciências Econômicas', id: 10 },
    { name: 'Comércio Exterior', id: 11 },
    { name: 'Dança', id: 12 },
    { name: 'Design', id: 13 },
    { name: 'Design de Interiores', id: 14 },
    { name: 'Direito', id: 15 },
    { name: 'Educação Física', id: 16 },
    { name: 'Enfermagem', id: 18 },
    { name: 'Engenharia Agronômica', id: 19 },
    { name: 'Engenharia Ambiental', id: 20 },
    { name: 'Engenharia Civil', id: 21 },
    { name: 'Engenharia da Computação', id: 22 },
    { name: 'Engenharia de Alimentos', id: 23 },
    { name: 'Engenharia de Bioprocessos', id: 24 },
    { name: 'Engenharia de Controle', id: 25 },
    { name: 'Engenharia de Produção', id: 26 },
    { name: 'Engenharia Elétrica', id: 27 },
    { name: 'Engenharia Mecânica', id: 28 },
    { name: 'Engenharia Química', id: 29 },
    { name: 'Estética e Cosmética', id: 30 },
    { name: 'Farmácia', id: 31 },
    { name: 'Filosofia', id: 32 },
    { name: 'Fisioterapia', id: 33 },
    { name: 'Fonoaudiologia', id: 34 },
    { name: 'Gastronomia', id: 35 },
    { name: 'Gestão Comercial', id: 36 },
    { name: 'Gestão da Qualidade', id: 37 },
    { name: 'Gestão de Equinocultura', id: 38 },
    { name: 'Gestão de RH', id: 39 },
    { name: 'Gestão Financeira', id: 40 },
    { name: 'História', id: 41 },
    { name: 'Hotelaria', id: 42 },
    { name: 'Jogos Digitais', id: 43 },
    { name: 'Jornalismo', id: 44 },
    { name: 'Letras: Português/Inglês', id: 45 },
    { name: 'Logística', id: 46 },
    { name: 'Marketing', id: 47 },
    { name: 'Matemática', id: 48 },
    { name: 'Medicina Veterinária', id: 49 },
    { name: 'Moda', id: 50 },
    { name: 'Música', id: 51 },
    { name: 'Nutrição', id: 52 },
    { name: 'Odontologia', id: 53 },
    { name: 'Pedagogia', id: 54 },
    { name: 'Processos Gerenciais', id: 55 },
    { name: 'Psicologia', id: 56 },
    { name: 'Publicidade e Propaganda', id: 57 },
    { name: 'Química', id: 58 },
    { name: 'Química Industrial', id: 59 },
    { name: 'Relações Internacionais', id: 60 },
    { name: 'Relações Públicas', id: 61 },
    { name: 'Teatro', id: 62 },
    { name: 'Terapia Ocupacional', id: 63 },
  ];

  constructor() {}
}
